### PR TITLE
Add support for reading extra coordinates

### PR DESCRIPTION
**Pull request by aurghs**
Currently, it is possible to define in `dataset.open_file` interface additional _attributes_ to be read, but not additional _coordinates_. 
With this PR we add the possibility to select extra _coordinates_ to be read.

This feature has been required by the CDS team for the new `grib_to_netcdf`,  to allow reading `experimentVersionNumber`  as a coordinate depending on time using Xarray. This is an example using the sample data in cfgrib tests directory:

``` python
>>> test_data = "tests/sample-data/era5-levels-members.grib"
>>> xr.open_dataset(test_data, engine="cfgrib", backend_kwargs={"extra_coords":{"experimentVersionNumber": "time"}}

<xarray.Dataset>
Dimensions:                  (isobaricInhPa: 2, latitude: 61, longitude: 120, number: 10, time: 4)
Coordinates:
  * number                   (number) int64 0 1 2 3 4 5 6 7 8 9
  * time                     (time) datetime64[ns] 2017-01-01 ... 2017-01-02T...
    step                     timedelta64[ns] ...
  * isobaricInhPa            (isobaricInhPa) int64 850 500
  * latitude                 (latitude) float64 90.0 87.0 84.0 ... -87.0 -90.0
  * longitude                (longitude) float64 0.0 3.0 6.0 ... 354.0 357.0
    valid_time               (time) datetime64[ns] ...
    experimentVersionNumber  (time) <U4 ...
Data variables:
    z                        (number, time, isobaricInhPa, latitude, longitude) float32 ...
    t                        (number, time, isobaricInhPa, latitude, longitude) float32 ...
```

- Add keyword `extra_coords` in `dataset.open_file`: supported only coordinates indexed by one dimension.
- Add tests.

### CODE REVIEW

**Review by alexamici — APPROVED** [review]

**Comment by iainrussell** [comment]
Hi @aurghs , I'm sure I'm just having a 'slow' day, but could you add a little more explanation of what/why this is doing? I'm not sure I understand the use case.
Thanks, Iain

**Comment by alexamici** [comment]
@iainrussell the change is more general, but the current use case is ERA5 as downloaded from the CDS has mixed `experimentVersionNumber`  because times older that a couple of months are from the validate ERA5 and times more recent that that are from ERA5T. Without this there's no way in *xarrray* to know which times are from ERA5T, and thus subject to change.

**Comment by iainrussell** [comment]
Thanks for the explanation @alexamici , especially the startStep and endStep!

**Review by iainrussell — APPROVED** [review]
Looks like it could be useful in a few cases,  nice work!

**Pull request merged**
