### PR TITLE
Add support to specify key type and always decode level as float

### LINKED ISSUE #195: GFS: Missing levels for sigmaLayer and depthBelowLandLayer
cfgrib seems to miss some levels for the level types `sigmaLayer` and `depthBelowLandLayer`.

I'm working with this grib file: https://noaa-gfs-bdp-pds.s3.amazonaws.com/gfs.20210115/00/gfs.t00z.pgrb2.0p25.f003

`wgrib2 -lev ~/Downloads/gfs.t00z.pgrb2.0p25.f003` shows four levels for each of these level types:

```
425:224793214:0-0.1 m below ground
427:225650288:0.1-0.4 m below ground
429:226508191:0.4-1 m below ground
431:227363072:1-2 m below ground

558:309354159:0.33-1 sigma layer
559:310143600:0.44-1 sigma layer
560:310922234:0.72-0.94 sigma layer
561:311736866:0.44-0.72 sigma layer
```

Reading the same file with cfgrib results in only two:

```python
import cfgrib

ds = cfgrib.open_datasets("gfs.t00z.pgrb2.0p25.f003")

d = next(d for d in ds if 'depthBelowLandLayer' in d.variables)
d.depthBelowLandLayer
# <xarray.IndexVariable 'depthBelowLandLayer' (depthBelowLandLayer: 2)>
# array([0, 1])
# Attributes:
#     long_name:      soil depth
#     units:          m
#     positive:       down
#     standard_name:  depth

d = next(d for d in ds if 'sigmaLayer' in d.variables)
d.sigmaLayer
# <xarray.IndexVariable 'sigmaLayer' (sigmaLayer: 2)>
# array([0, 1])
# Attributes:
#     long_name:  original GRIB coordinate for key: level(sigmaLayer)
#     units:      1

d.r.shape
# (2, 721, 1440)
```

### PR DESCRIPTION
**Pull request by alexamici**
With this change you can optionally specify the key type when using `Message.__getitem__` like:

```
>>> msg["level:float"]
1.0
>>> msg["level:int"]
1
>>> msg["level"]
1
```

Then the `level` key is decoded as `float` in order to close #195 . Note that this is a **significant user-visible change** but I think it is the best default.

### CODE REVIEW

**Comment by iainrussell** [comment]
Sorry @alexamici I missed this PR. It looks good to me, but it would look even better if there were some tests, if I may be so cheeky  :)

**Comment by alexamici** [comment]
I'm now hesitant to add this feature to *cfgrib* as it really looks like a lower level functionality. @shahramn do you have a way to specify the target data type in the key, like `msg["level:float"]`. Would you be interested in addign this functionality to *eccodes-python*?

**Comment by shahramn** [comment]
> I'm now hesitant to add this feature to _cfgrib_ as it really looks like a lower level functionality. @shahramn do you have a way to specify the target data type in the key, like `msg["level:float"]`. Would you be interested in addign this functionality to _eccodes-python_?

We already have a way of passing in the type information. For example:
```
% python3
>>> import eccodes
>>> f = open(input, 'rb')
>>> gid = eccodes.codes_grib_new_from_file(f)
>>> print( eccodes.codes_get(gid, 'level') )
65
>>> print( eccodes.codes_get(gid, 'level', float) )
65.4
>>> print( eccodes.codes_get_double(gid, 'level') )
65.4
```

**Comment by alexamici** [comment]
@iainrussell I added the tests for the generic functionality. This is ready to merge for me.

**Review by iainrussell — APPROVED** [review]
Looks good to me, great that eccodes has such a nice interface to allow this to work so conveniently!

**Pull request merged**
