### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by shahramn**
Fix the broken link to download era5-levels-members.grib
See https://github.com/ecmwf/cfgrib/issues/365

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/cfgrib?pullRequest=366) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/cfgrib?pullRequest=366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/cfgrib?pullRequest=366) it.</sub>

**Comment by iainrussell** [comment]
Thank you @shahramn!

**Comment by StephanSiemen** [comment]
@shahramn thanks for looking after this, but the format of the first link you changed renders a bit strange ... perhaps a problem with the format?

Screenshot 2024-01-21 at 10 50 35

**Comment by iainrussell** [comment]
Thanks for spotting it Stephan, I've fixed that now!

**Pull request merged**
